default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: "name_trivia_api_dev"
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>

test:
  <<: *default
  database: name_trivia_api_test

production:
  <<: *default
  database: "name_trivia_api_prod"
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
